Update CONTRIBUTORS.md
blwatkins/CRCP3320-1247 pull request #1
Opened 2024-09-28 21:26 UTC by mariamuradd

2024-09-28 23:04 UTC, blwatkins requested changes
One small change to make, but overall it looks good.

2024-09-28 23:04 UTC, blwatkins commented on CONTRIBUTORS.md
> +[maria murad](https://github.com/mariamuradd)
Could you please move this to line 3 or 4 and leave line 2 blank?

2024-09-29 03:50 UTC, mariamuradd commented
changed to line 4!

2024-09-29 23:17 UTC, blwatkins commented
I believe if you perform a pull request of your main branch into your patch-1 branch, I should be able to see the change here.  You can also close this pull request and open a new one with your changes, if you would prefer.

2024-09-29 23:46 UTC, closed without merging