Added name to contributors.md
blwatkins/CRCP3320-1247 pull request #38
Opened 2024-10-18 18:34 UTC by jayeryden

This should add just my name to the contributors file

2024-10-18 19:56 UTC, blwatkins requested changes
Please fix the merge conflicts in this file.  Check the "Files changed" tab after you create or your pull request to make sure that the changes match what you expect.

Changes in this pull request should not remove changes made by other students (see docs/portfolios.md changes).

Comment Date: Friday, October 18.

2024-10-18 19:56 UTC, blwatkins commented on docs/portfolios.md
> -***[Tanner Shepherd](https://tzshepherd.github.io/)***
Changes in this file should not remove other students' entries.

2024-10-18 20:17 UTC, jayeryden commented on docs/portfolios.md
> -***[Tanner Shepherd](https://tzshepherd.github.io/)***
How do I fix this error? I didn't think I made these changes on my local machine and I have pulled so my branch is up to date. How should I resolve this? I see the changes in Files changed but I'm not sure how to fix the merge conflict and undo what I did.

2024-10-19 19:41 UTC, jayeryden commented
Going to close this pull request and submit a replacement

2024-10-19 19:41 UTC, closed without merging